import React from 'react'
import Navbar from '../../Compunents/Navbar'
import Footer from '../../Compunents/Footer'

const Terms = () => {
  return (
    <>

<div className="bg-black opacity-80 relative">
                <Navbar />

            </div>



            <div className='w-11/12 2xl:w-4/6  py-10  mx-auto'>

            <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">
            TERMS & CONDITIONS
</h2>

Last updated on July 27,2024

<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">


General Terms
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

By accessing and placing an order with EUaffairs, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and EUaffairs. Under no circumstances shall the EUaffairs team be liable for any direct, indirect, special, incidental, or consequential damages, including but not limited to loss of data or profit, arising out of the use or inability to use the materials on this site, even if the EUaffairs team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair, or correction of equipment or data, you assume any costs thereof. EUaffairs will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the right to change prices and revise the resource usage policy at any moment.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

License
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

EUaffairs grants you a revocable, non-exclusive, non-transferable, limited license to use the website strictly in accordance with the terms of this Agreement. These Terms & Conditions are a contract between you and EUaffairs (referred to in these Terms & Conditions as "EUaffairs", "us", "we", or "our"), the provider of the EUaffairs website and the services accessible from the EUaffairs website (which are collectively referred to in these Terms & Conditions as the "EUaffairs Service"). You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the EUaffairs Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">


Definitions and Key Terms
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

To help explain things as clearly as possible in these Terms & Conditions, every time any of these terms are referenced, they are strictly defined as:
<br />
- Cookie: A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.

<br />
- Company: When these terms mention “Company,” “we,” “us,” or “our,” it refers to EUaffairs, (Tongersestraat 17 6211LL Maastricht), that is responsible for your information under these Terms & Conditions.
<br />
- Country: Where EUaffairs or the owners/founders of EUaffairs are based, in this case, the Netherlands.
<br />
- Device: Any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit EUaffairs and use the services.
<br />
- Service: Refers to the service provided by EUaffairs as described in the relative terms (if available) and on this platform.
<br />
- Third-party service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
<br />
- Website: EUaffairs's site, which can be accessed via this URL: euaffairs.org. 
<br />
- You: A person or entity that is registered with EUaffairs to use the Services.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Information We Collect
</h2>

<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

We reserve the right to collect and store the following information from you:
<br />
- Name: Your full first name as indicated in the specific field on our website. This helps us identify you and personalize your experience.
<br />
- Surname: Your full last name as indicated in the specific field on our website. This is used for identification and personalization purposes.
<br />
- Avatar: An image or icon that you can upload to represent yourself on your profile. This helps personalize your experience and allows others to recognize you.
<br />
- Email: Your email address as indicated in the specific field on our website. This is used for communication purposes, including sending updates, notifications, and promotional offers.
<br />
- Hashed Password: Hashed passwords are stored to enable users to access their accounts. These passwords cannot be unhashed, ensuring that EUaffairs employees cannot read or access the original passwords.
<br />
- Description: A brief description or bio that you can provide about yourself. This helps personalize your profile and allows others to know more about you.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Communication
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

By providing your email address, you agree that EUaffairs has the right to contact you via email or any other means of communication, including but not limited to, updates, promotional offers, and other information related to the service. If you wish to opt out of receiving such communications, you may do so at any time by contacting us via the email provided at the end of this agreement to inform us that you do not want to be contacted.

</p>




<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">


Restrictions
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

You agree not to, and you will not permit others to:
<br />- License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or otherwise commercially exploit the website or make the platform available to any third party.
<br />- Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.
<br />- Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) of EUaffairs or its affiliates, partners, suppliers, or the licensors of the website.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Payment
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

If you pay for any of our one-time payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges, and billing terms in effect at the time that each fee or charge is due and payable. Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider. By providing EUaffairs with your credit card number and associated payment information, you agree that EUaffairs is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to EUaffairs hereunder and that no additional notice or consent is required. You agree to immediately notify EUaffairs of any change in your billing address or the credit card used for payment hereunder. EUaffairs reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization’s administrator(s). Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts shall be the responsibility of and paid for by you. No contract will exist between you and EUaffairs for the Service until EUaffairs accepts your order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication. You are responsible for any third-party fees that you may incur when using the Service.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Return and Refund Policy
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

Thanks for shopping at EUaffairs. We appreciate the fact that you like to use the services we provide. We also want to make sure you have a rewarding experience while you are exploring, evaluating, and purchasing our services. As with any shopping experience, there are terms and conditions that apply to transactions at EUaffairs. We will be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at EUaffairs, you agree to the terms along with EUaffairs’s Privacy Policy. If, for any reason, you are not completely satisfied with any service that we provide, do not hesitate to contact us and we will discuss any of the issues you are going through with our product.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">


Your Suggestions
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">


Any feedback, comments, ideas, improvements, or suggestions (collectively, "Suggestions") provided by you to EUaffairs with respect to the website shall remain the sole and exclusive property of EUaffairs. EUaffairs shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
</p>

<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

*our Consent
</h2>

<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

We have updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it is being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Links to Other Websites
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

These Terms & Conditions apply only to the Services. The Services may contain links to other websites not operated or controlled by EUaffairs. We are not responsible for the content, accuracy, or opinions expressed in such websites, and such websites are not investigated, monitored, or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, are subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.

</p>

<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Cookies
</h2>
<p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">

EUaffairs uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website, and they are essential for its use, such as for logging in. We do not use third-party cookies. Without these
</p>



            </div>
            <Footer/>
      
    </>
  )
}

export default Terms
