import React from 'react'
import Navbar from '../../Compunents/Navbar'
import Footer from '../../Compunents/Footer'

const PrivacyPolicy = () => {

    return (
        <>
            {/* <div className=" relative w-100   bg-no-repeat bg-cover">
        <Navbar />
      </div> */}
            <div className="bg-black opacity-80 relative">
                <Navbar />

            </div>



            <div className='w-11/12 2xl:w-4/6  py-10  mx-auto'>


                <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">
                    PRIVACY POLICY
                </h2>

                <p className="lg:text-xl font-normal text-ptheme text-md text-justify md:text-left">
                    EUaffairs ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by EUaffairs. This Privacy Policy applies to our website and its associated subdomains (collectively, our “Service”) alongside our application, EUaffairs. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.



                    <br />
                    Definitions and key terms

                    <br />
                    To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:

                    <br />
                    - Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
                    <br />
                    - Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to EUaffairs (François de Veyestraat 8B 6221 AB Maastricht), that is responsible for your information under this Privacy Policy.
                    <br />
                    - Country: where EUaffairs or the owners/founders of EUaffairs are based; in this case, the Netherlands.
                    <br />
                    - Customer: refers to the company, organization, or person that signs up to use the EUaffairs Service to manage relationships with your consumers or service users.
                    <br />
                    - Device: any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit EUaffairs and use the services.
                    <br />
                    - IP address: Every device connected to the Internet is assigned a number known as an Internet Protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
                    <br />
                    - Personnel: refers to those individuals who are employed by EUaffairs or are under contract to perform a service on behalf of one of the parties.
                    <br />
                    - Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                    <br />
                    - Service: refers to the service provided by EUaffairs as described in the relative terms (if available) and on this platform.
                    <br />
                    - Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                    <br />
                    - Website: EUaffairs’s site, which can be accessed via this URL: [https://www.euaffairs.org]
                    <br />
                    - You: a person or entity that is registered with EUaffairs to use the Services.
                    <br />


                </p>




                <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">
                    What Information Do We Collect?
                </h2>








                <p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>



                    We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey, or fill out a form.
                    <br />
                    - Name: Your full first name as indicated in the specific field on our website. This helps us identify you and personalize your experience.
                    <br />
                    - Surname: Your full last name as indicated in the specific field on our website. This is used for identification and personalization purposes.
                    <br />
                    - Avatar: An image or icon that you can upload to represent yourself on your profile. This helps personalize your experience and allows others to recognize you.
                    <br />
                    - Email: Your email address as indicated in the specific field on our website. This is used for communication purposes, including sending updates, notifications, and promotional offers.
                    <br />
                    - Hashed Password: Hashed passwords are stored to enable users to access their accounts. These passwords cannot be unhashed, ensuring that EUaffairs employees cannot read or access the original passwords.
                    <br />
                    - Description: A brief description or bio that you can provide about yourself. This helps personalize your profile and allows others to know more about you.
                    <br />


                </p>






                <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

                    When does EUaffairs use end user information from third parties?
                </h2>
                <p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>
                    EUaffairs will collect End User Data necessary to provide the EUaffairs services to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
                </p>



                <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

                    When does EUaffairs use customer information from third parties?
                </h2>
                <p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

                    We receive some information from third parties when you contact us. We also occasionally collect information that is made publicly available on social media websites.

                </p>






                <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">


                    Do we share the information we collect with third parties?
                </h2>

                <p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

                    We may engage trusted third-party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, email management, storage marketing, credit card processing, customer service, and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.

                    <br />
                    We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website in a shared location, and the type of device used to visit the website. They may aggregate information about our advertising and what you see on the website and then provide auditing, research, and reporting for us and our advertisers.
                    <br />

                    We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal processes (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules, and regulations.




                </p>


                <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

                Where and when is information collected from customers and end users?
                </h2>

                <p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

EUaffairs will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

How Do We Use The Information We Collect?
</h2>

<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

Any of the information we collect from you may be used in one of the following ways:
<br />- To personalize your experience (your information helps us to better respond to your individual needs).
<br />- To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you).
<br />- To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs).
<br />- To process transactions.
<br />- To administer a contest, promotion, survey, or other site features.
<br />
- To send informative and promotional emails.


</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

How Do We Use Your Email Address?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>


By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe options included in the respective email. We only send emails to people who have authorized us to contact them, either directly or through a third party. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. 
</p>


                   


<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>


<span className='text-theme text-2xl my-3'>
 Note:</span> If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

How Long Do We Keep Your Information?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

We keep your information only so long as we need it to provide EUaffairs to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

How Do We Protect Your Information?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

<br />We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems and are required to keep the information confidential. 

<br />After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to EUaffairs or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
</p>

<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Could My Information Be Transferred to Other Countries?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

EUaffairs is incorporated in the Netherlands. Information collected via our website, through direct interactions with you, or from the use of our services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Is the Information Collected Through the EUaffairs Service Secure?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes, or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standard used to measure our compliance with that duty.
</p>



<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Can I Update or Correct My Information?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>

The rights you have to request updates or corrections to the information EUaffairs collects depend on your relationship with EUaffairs. Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by canceling your account. Such updates, corrections, changes, and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change, or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times. You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use and other readily searchable media will be updated, corrected, changed, or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting us via email.
<br />
<span className='text-theme text-2xl my-3'>

Sale of Business
</span>
<br />

We reserve the right to transfer information to a third party in the event of a sale, merger, or other transfer of all or substantially all of the assets of EUaffairs or any of its Corporate Affiliates (as defined herein), or that portion of EUaffairs or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization, or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.
<br />
<span className='text-theme text-2xl my-3'>


Affiliates
</span>
<br />
We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with EUaffairs, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
<br />
<span className='text-theme text-2xl my-3'>


Governing Law
</span>
<br />

This Privacy Policy is governed by the laws of the Netherlands without regard to its conflict of laws provisions. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy. The laws of the Netherlands, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws. By using EUaffairs or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
<br />
<span className='text-theme text-2xl my-3'>


Your Consent
</span>
<br />

We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using EUaffairs, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
<br />
<span className='text-theme text-2xl my-3'>


Links to Other Websites
</span>
<br />

This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by EUaffairs. We are not responsible for the content, accuracy, or opinions expressed in such websites, and such websites are not investigated, monitored, or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, are subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
<br />
<span className='text-theme text-2xl my-3'>



Advertising
</span>
<br />

This website may contain third-party advertisements and links to third-party sites. EUaffairs does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties. Third-party advertisements and links to other sites where goods or services are advertised are not endorsements or recommendations by EUaffairs of the third-party sites, goods, or services. EUaffairs takes no responsibility for the content of any of the ads, promises made, or the quality/reliability of the products or services offered in all advertisements.
<br />
<span className='text-theme text-2xl my-3'>


Cookies
</span>
<br />

EUaffairs uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website, and they are essential for its use, such as for logging in. We do not use third-party cookies. Without these cookies, certain functionality like videos may become unavailable, or you would be required to enter your login details every time you visit the website, as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all.
<br />
<span className='text-theme text-2xl my-3'>


Remarketing Services
</span>
<br />

We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're “following” people around the internet by serving ads on the websites and platforms they use most.
<br />
<span className='text-theme text-2xl my-3'>


Payment Details
</span>
<br />

In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.
<br />
<span className='text-theme text-2xl my-3'>


Kids' Privacy
</span>
<br />

We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.
<br />
<span className='text-theme text-2xl my-3'>


Changes to Our Privacy Policy
</span>
<br />

We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.
<br />
<span className='text-theme text-2xl my-3'>


Third-Party Services
</span>
<br />

We may display, include, or make available third-party content (including data, information, applications, and other products services) or provide links to third-party websites or services ("Third-Party Services"). You acknowledge and agree that EUaffairs shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. EUaffairs does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.


<br />
Information about General Data Protection Regulation (GDPR)

<br />We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy

 <br />
 Policy we are going to explain exactly how and why this data is collected, and how we maintain this data under protection from being replicated or used in the wrong way.
 </p>

 <h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

What is GDPR?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>
GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and enhances the control the EU residents have over their personal data. The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our customers’ data is important irrespective of where they are located, which is why we have implemented GDPR controls as our baseline standard for all our operations worldwide.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

What is Personal Data?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>
Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity. The Data Protection Principles include requirements such as: Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect. Personal data should only be collected to fulfill a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it. Personal data should be held no longer than necessary to fulfill its purpose. People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.
</p>
<h2 className="text-theme text-3xl md:text-4xl lg:text-5xl font-semibold my-5">

Why is GDPR Important?
</h2>
<p className='lg:text-xl font-normal text-ptheme text-md text-justify md:text-left'>
GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond these facts, it's simply the right thing to do. At EUaffairs we strongly believe that your data privacy is very important and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.

<br />Individual Data Subject's Rights - Data Access, Portability, and Deletion

<br />
We are committed to helping our customers meet the data subject rights requirements of GDPR. EUaffairs processes or stores all personal data in fully vetted, DPA-compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days. We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve, and remove personal data. We've got you! We've been set up as self-service from the start and have always given you access to your data and your customers' data. Our customer support team is here for you to answer any questions you might have about working with the API.
</p>


            </div>

            <Footer/>
        </>
    )
}

export default PrivacyPolicy
